# Site settings
title: Rogers Mukiibi Blog
email: 
description: "Electrical Engineering Student"
baseurl: ""
url: "https://rogerzmukiibi.github.io"
twitter_username: rodgerzmukiibi
github_username:  rogerzmukiibi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge